server:
  port: ${PORT:8089}
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: ${PROFILES:local}
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
management:
  endpoint:
    health:
      show-components: always
  health:
    rabbit:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus